apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris-production
  template:
    metadata:
      labels:
        app: tetris-production
    spec:
      containers:
        - name: tetris
          image: gcr.io/fiery-palace-430720-j1/tetris-react:latest # Updated to use your GCR image
          ports:
            - containerPort: 3000 # Use port 3000
