apiVersion: v1
kind: Service
metadata:
  name: tetris-service-production
spec:
  selector:
    app: tetris-production
  ports:
    - protocol: TCP
      port: 80 # Expose port 80
      targetPort: 3000
  type: LoadBalancer
